Create pr_template.md
f-lab-edu/toss-tech-project pull request #1
Opened 2023-10-19 00:49 UTC by andyhan-23

추후에 작성할 pull_request를 위해 pull_request 템플릿을 추가하였습니다.

2023-10-19 13:28 UTC, f-lab-woody commented on .github/pr_template.md
> +
revert는 어디있죠?

2023-10-19 13:28 UTC, f-lab-woody commented on .github/pr_template.md
> +- [ ] 🎨 Style (코드 의미에 영향을 주지 않는 변경사항)
코드의미에 영향을 주지 않는 변경사항이라는 말이 무슨말일까요?
코드의미가 뭘뜻하죠?

2023-10-19 13:28 UTC, f-lab-woody commented on .github/pr_template.md
> +- [ ] 📦 Chore (빌드 부분 혹은 패키지 매니저 수정사항)
릴리즈 및 린트는 어디들어가죠?

2023-10-19 13:30 UTC, f-lab-woody commented
PR template을 작성하는 커밋엔 템플릿을 활용하지 않은 이유가 있을까요?

2023-10-19 14:48 UTC, andyhan-23 commented on .github/pr_template.md
> +
추가하였습니다.

2023-10-19 14:53 UTC, andyhan-23 commented on .github/pr_template.md
> +- [ ] 🎨 Style (코드 의미에 영향을 주지 않는 변경사항)
코드로 인해 기능 구현을 할때 구현에 영향을 미치지 않는 변수명 등이 적절하지 않은 경우 변경하려 하였습니다.

2023-10-19 14:53 UTC, andyhan-23 commented on .github/pr_template.md
> +- [ ] 📦 Chore (빌드 부분 혹은 패키지 매니저 수정사항)
추가 하였습니다.

2023-10-19 14:56 UTC, andyhan-23 commented
수정후 작성된 커밋은 템플릿을 반영하여 올렸습니다.

2023-10-19 23:43 UTC, f-lab-woody commented on .github/pr_template.md
> +- [ ] 🎨 Style (코드 의미에 영향을 주지 않는 변경사항)
변수명이 코드의미에 영향을 주는게 아닌가요?
변수명이야말로 코드의미를 가장 잘 나타내는 요소라고 생각합니다

2023-10-19 23:46 UTC, f-lab-woody commented on .github/pr_template.md
> +- [ ] ⏩ Revert (뒤로가기)
Revert는 뒤로가기보단 되돌리기가 좀더 좋은 표현같아요

2023-10-19 23:46 UTC, f-lab-woody commented on .github/pr_template.md
> +- [ ] 📦 Chore (Release)
Chore는 Release만 들어가나요?

2023-10-19 23:46 UTC, f-lab-woody commented on .github/pr_template.md
> +- [ ] 📦 Chore (Release)
다른건 다 한국말로 설명되어있는데 왜 Release만 영어로 쓰여져있을까요?

2023-10-19 23:46 UTC, f-lab-woody commented on .github/pr_template.md
> +- [ ] 특히 이해하기 어려운 부분에 대해서는 코드에 주석을 달았습니다.
좋지않습니다. 코드에 특히 이해하기 어려운 부분이 있어서는 안됩니다.

2023-10-19 23:46 UTC, f-lab-woody commented on .github/pr_template.md
> +- [ ] 로컬 화경에서 충분히 테스트를 하였습니다.
충분히 테스트를했는지 어떻게 판단하죠?

2023-10-20 00:01 UTC, andyhan-23 commented on .github/pr_template.md
> +- [ ] ⏩ Revert (뒤로가기)
수정 하였습니다.

2023-10-20 00:07 UTC, andyhan-23 commented on .github/pr_template.md
> +- [ ] 특히 이해하기 어려운 부분에 대해서는 코드에 주석을 달았습니다.
해당 부분은 삭제하였습니다.

2023-10-20 00:08 UTC, andyhan-23 commented on .github/pr_template.md
> +- [ ] 로컬 화경에서 충분히 테스트를 하였습니다.
이 용어 또한 애매하다고 생각 들어 삭제 하였습니다.

2023-10-20 00:15 UTC, andyhan-23 commented on .github/pr_template.md
> +- [ ] 🎨 Style (코드 의미에 영향을 주지 않는 변경사항)
수정하였습니다.

2023-10-20 00:39 UTC, andyhan-23 commented on .github/pr_template.md
> +- [ ] 📦 Chore (Release)
제가 Release라고 적은 이유는 배포의 의미로서 작성하였습니다. 배포의 종류로는 크게 3가지인 Release, Deploy, Distribute로 알아봤는데 그 중에서도 저희가 만드는 프로젝트는 기존의 버전을 새롭게 만드는 것이라 생각이 들어 3가지 용어 중에 릴리즈를 택하였습니다.  저렇게 하나만 적는것보다는 3가지 용어를 모두 적는게 더 좋을까요?

2023-10-20 02:41 UTC, f-lab-woody commented on .github/pr_template.md
> +- [ ] 📦 Chore (Release)
Release로 적은 이유가 궁금하진 않았고, chore에 들어갈게 더 많지 않을까 해서 여쭤봤던거예요.
> 저렇게 하나만 적는것보다는 3가지 용어를 모두 적는게 더 좋을까요?
Release, Deploy, Distribute각자 다른의미를 가지고있는데, 어떻게 다른지 공부해보시면 좋을것같아요.

왜 Release만 영어로 쓰여져있냐는 말은 릴리즈 뿐만아니라 다른 카테고리들 모두 문장의 형식이 달라서 말씀드린겁니다. 통일해주시면 좋겠습니다. (아니면 다 빼도 좋구요)

2023-10-20 02:49 UTC, f-lab-woody requested changes

2023-10-20 02:49 UTC, f-lab-woody commented on .github/pr_template.md
> +- [ ] 테크 스펙에 해당하는 내용을 변경하였습니다.
> 테크 스펙에 해당하는 내용을 변경하였습니다.
우리가 해결하는 문제에대한 커밋은 테크스펙안에 포함되어있어야하지 않나요?
항상 체크가 되어있을것같은데, 굳이적어두었다라는 생각이듭니다.

2023-10-20 02:49 UTC, f-lab-woody commented on .github/pr_template.md
> +- [ ] Preview Page
> Preview Page
이건 뭘뜻하는걸까요?

2023-10-20 02:49 UTC, f-lab-woody commented on .github/pr_template.md
> +Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
이 문장이 여기서 필요한가요?

2023-10-20 02:49 UTC, f-lab-woody commented on .github/pr_template.md
> +Please include a summary of the changes and the related issue.
이 문장이 여기서 필요한가요?

2023-10-20 02:49 UTC, f-lab-woody commented on .github/pr_template.md
> +- [ ] ⚙️ Rename (변수명 변경)
> 🎨 Style (CSS 및 UI 디자인 변경)
정말 스타일변경인가요? 스타일은 feat안에 포함되어야하지 않나요?
> ⚙️ Rename (변수명 변경)
refactor랑 어떻게 다르죠?

2023-10-20 02:49 UTC, f-lab-woody commented on .github/pr_template.md
> +- [ ] ⚙️ Rename (변수명 변경)
해당 파일은 semantic commit message를 참고하시면 좀 더 쉽게 적용하실 수 있습니다.

https://gist.github.com/joshbuchea/6f47e86d2510bce28f8e7f42ae84c716#file-semantic-commit-messages-md

2023-10-20 23:03 UTC, andyhan-23 commented on .github/pr_template.md
> +- [ ] 📦 Chore (Release)
모두 빼는 것으로 수정하였습니다.

2023-10-20 23:16 UTC, andyhan-23 commented on .github/pr_template.md
> +- [ ] Preview Page
Preview Page란 이 코드를 어떻게 테스트 할 수 있는가에 대하여 테스트 코드로 테스트를 한다던지 아니면 step by step으로 순서를 작성해 요청 가이드를 따라오면 페이지가 화면에 보일수 있다 라는 의미로 미리 리뷰어가 실제 테스트를 안해봐도 만들어진 화면을 스크린샷으로 설정하여 보여주는 것을 의미합니다. 

- 근데 이렇게 작성을 하다 보니 주제랑 많이 반대되는것 같아 How has this been tested? 가 아니라 How to run? 으로 바꾸려 합니다.

2023-10-20 23:17 UTC, andyhan-23 commented on .github/pr_template.md
> +- [ ] 테크 스펙에 해당하는 내용을 변경하였습니다.
저도 멘토님 말에 동의하여 제거하는 방향으로 수정하였습니다.

2023-10-20 23:18 UTC, andyhan-23 commented on .github/pr_template.md
> +Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
필요없다고 생각이 들어 삭제하였습니다.

2023-10-20 23:18 UTC, andyhan-23 commented on .github/pr_template.md
> +Please include a summary of the changes and the related issue.
이 문장 또한 필요 없다고 생각이 들어 삭제하였습니다.

2023-10-20 23:29 UTC, andyhan-23 commented on .github/pr_template.md
> +- [ ] ⚙️ Rename (변수명 변경)
해당 파일을 참고해보니, Style 안에 들어가야 하는 역할들이야 말로 코드 변경에 영향을 미치지 않는 누락된 세미콜론 이라는 것들이 있을시 포함하는 역할을 하는 것이라 생각이 듭니다. 근데 저희가 진행할 프로젝트는 eslint, prettier를 사용해 코드 포맷팅을 해주는것으로 알고 있는데 굳이 style이 필요 할까 싶습니다. 
- 그래서 저의 의견은 Style을 제거하려 하는데 멘토님의 의견이 궁금합니다.
- Rename이랑 refactor랑 같다고 판단히 들어 Rename을 삭제 후 code refactor로 통일하였습니다.

2023-10-20 23:29 UTC, andyhan-23 commented on .github/pr_template.md
> +Please include a summary of the changes and the related issue.
필요없다고 생각이 들어 제거하였습니다.

2023-10-21 03:37 UTC, f-lab-woody commented on .github/pr_template.md
> +- [ ] Preview Page
재혁님, 영어를 쓰시는건 좋습니다. 근데 계속 의미가 달라집니다.
실행방법과 테스트를했는지는 완전히 다른 이야기 아닐까요?
굳이 영어를 고집하는 이유가 있을까요?

저라면 Preview Page보단 
깔끔하게 로컬환경에서 수동 테스트 진행이라고할것같아요.

2023-10-21 03:37 UTC, f-lab-woody commented on .github/pr_template.md
> +- [ ] ⚙️ Rename (변수명 변경)
기존에 커밋내용을 보면 "코드는 이 프로젝트의 스타일 지침을 따랐습니다."라는 체크버튼이 있었는데, 
([링크](https://gist.github.com/joshbuchea/6f47e86d2510bce28f8e7f42ae84c716))내용은 여기서 나오는 스타일을 말하는것 아닐까요?

2023-10-21 03:39 UTC, f-lab-woody commented on .github/pr_template.md
> +- [ ] Preview Page
^ 위에는 Test 코드 작성 이라고 행위를 나타내셨는데, 아래는 Preview Page라고 쓰셨습니다.

이부분은 제가 이전에 드렸던 코멘트와 같은결인것 같아요.
https://github.com/f-lab-edu/toss-tech-project/pull/1#discussion_r1366379666

2023-10-22 00:45 UTC, andyhan-23 commented on .github/pr_template.md
> +- [ ] Preview Page
수정 하였습니다.

2023-10-22 00:46 UTC, andyhan-23 commented on .github/pr_template.md
> +- [ ] ⚙️ Rename (변수명 변경)
수정하였습니다.

2023-10-22 15:29 UTC, f-lab-woody approved these changes
LGTM

2023-10-23 00:40 UTC, merged