[Feat] 라우터 구현
f-lab-edu/toss-tech-project pull request #12
Opened 2023-11-02 20:08 UTC by andyhan-23

# 설명
- 브라우저 라우터를 구현했습니다.
- render, navigate, start 함수를 외부에서 사용할 수 있게 만들었습니다.
- `String.prototype.match()` 메서드를 사용해 현재 페이지 url이 정규표현식과 일치하면 배열을 반환하고, 일치하는 것이 없으면 null을 반환하는 것을 이용해 페이지 전환을 할 수 있게 구현했습니다.
## 무슨 종류의 PR인지?

- [X] 🕹️ Feat 
- [ ] 📌 Fix
- [ ] 🔖 Documentation Update
- [ ] 🎨 Style 
- [ ] 🔎 Code Refactor 
- [ ] ✅ Test 
- [ ] 🤖 Build 
- [ ] 📦 Chore
- [ ] ⏩ Revert 

# 어떻게 테스트 되었는가?

- [ ] 테스트 코드 작성
- [ ] 로컬환경에서 수동 테스트 진행

# 티켓 번호
[JAE-22](https://linear.app/jaehyeok/issue/JAE-22/[5]-%EB%9D%BC%EC%9A%B0%ED%84%B0-%EA%B5%AC%ED%98%84)

2023-11-03 01:46 UTC, f-lab-woody requested changes
관심사 분리가 안되어있습니다.

다시 하나하나 검토해주시고 이해안되는부분은 질문주세요.

2023-11-03 01:46 UTC, f-lab-woody commented on package-lock.json
>          "node": ">= 8"
이거 지금 메인에 들어가있는건가요?

맞다면 이것만 따로 먼저 요청주세요.

2023-11-03 01:46 UTC, f-lab-woody commented on src/router/index.js
> +import notFound from "../view/page/not-found";
얘혼자 왜 PascalCase가 아닌가요?

2023-11-03 01:46 UTC, f-lab-woody commented on src/router/index.js
> +import Main from "../view/page/main";
view -> views로 이름 변경해주세요

2023-11-03 01:46 UTC, f-lab-woody commented on src/router/index.js
> +//Controller를 통해 화면을 담당하는 부분은 추후 티켓에서 구현 예정입니다.티켓번호:JAE-24
nit, 위와같은 코멘트를 달 때는 //Todo: ...
이렇게 달아주시는게 좋습니다

2023-11-03 01:46 UTC, f-lab-woody commented on src/router/index.js
> +const root = document.querySelector("#app");
얘는 구현체 안쪽으로 들어가야하지 않나요?

2023-11-03 01:46 UTC, f-lab-woody commented on src/router/index.js
> +  new RegExp(`^${path.replace(/\//g, "\\/").replace(/:\w+/g, "(.+)")}$`);
패턴이 눈에 보기 어렵습니다.

constant로 따로 빼주세요

2023-11-03 01:46 UTC, f-lab-woody commented on src/router/index.js
> +const pathToRegex = path =>
해당 펑션은 테스터블한가요?

2023-11-03 01:46 UTC, f-lab-woody commented on src/router/index.js
> +const pathToRegex = path =>
더 좋은 네이밍은 없나요?

pathToRegex는 뭘의미하는건가요?

2023-11-03 01:46 UTC, f-lab-woody commented on src/router/index.js
> +const pathToRegex = path =>
유틸파일로 옮겨주시고, 테스트코드작성해주세요

2023-11-03 01:46 UTC, f-lab-woody commented on src/router/index.js
> +    return { route, isMatch };
매치 하지 않는 route를 왜 넣죠? 매치 안하면 안넣으면 되는거 아니예요?

2023-11-03 01:46 UTC, f-lab-woody commented on src/router/index.js
> +  const match = matchedRoutes.find(
불필요합니다

2023-11-03 01:46 UTC, f-lab-woody commented on src/router/index.js
> +    const isMatch = path.match(pathToRegex(route.path));
패스는 스트링을 예상했는데 오브젝트인가요?

2023-11-03 01:46 UTC, f-lab-woody commented on src/router/index.js
> +    const isMatch = path.match(pathToRegex(route.path));
타입이 어떻게 되죠?
js docs로 코멘트 위에 달아주세요

2023-11-03 01:46 UTC, f-lab-woody commented on src/router/index.js
> +  return match ? new match.route.Controller(root, param) : new notFound(root);
좀더 쉽게 정의할수있을것같아요.

2023-11-03 01:46 UTC, f-lab-woody commented on src/router/index.js
> +export const navigate = (path, param) => {
해당 파일안에 있어야하나요?

2023-11-03 01:56 UTC, f-lab-woody commented on src/router/index.js
> +import Main from "../view/page/main";
page -> pages

2023-11-03 05:58 UTC, andyhan-23 commented on package-lock.json
>          "node": ">= 8"
새로운 브랜치에서 작업후 특정 PR요청 드렸습니다.

2023-11-03 06:01 UTC, andyhan-23 commented on src/router/index.js
> +import notFound from "../view/page/not-found";
notFound 또한 파스칼케이스로 바꾸었습니다.

2023-11-03 06:03 UTC, andyhan-23 commented on src/router/index.js
> +import Main from "../view/page/main";
수정하였습니다.

2023-11-03 06:05 UTC, andyhan-23 commented on src/router/index.js
> +//Controller를 통해 화면을 담당하는 부분은 추후 티켓에서 구현 예정입니다.티켓번호:JAE-24
네 알겠습니다.

2023-11-03 11:16 UTC, andyhan-23 commented on src/router/index.js
> +  new RegExp(`^${path.replace(/\//g, "\\/").replace(/:\w+/g, "(.+)")}$`);
분리하였습니다.

2023-11-07 07:25 UTC, andyhan-23 commented on src/router/index.js
> +const root = document.querySelector("#app");
해당 코드는 구현체인 `app.js` 에서 실행하도록 하겠습니다.

2023-11-07 07:31 UTC, andyhan-23 commented on src/router/index.js
> +const pathToRegex = path =>
- pathToRegex는 예시로 /detail/1 과 같은 형태의 path를 /detail/:id 의 경로로 매칭할 수 있게 해주는 것입니다.
- pattern 이라는 네이밍으로 바꾸려 합니다.
- 테스트 코드 작성을 jest설치 관련 pr리뷰 부탁드립니다.
[JEST설치](https://github.com/f-lab-edu/toss-tech-project/pull/14)

2023-11-07 07:32 UTC, andyhan-23 commented on src/router/index.js
> +    return { route, isMatch };
수정하였습니다.

2023-11-07 07:33 UTC, andyhan-23 commented on src/router/index.js
> +  const match = matchedRoutes.find(
네, 삭제하였습니다.

2023-11-07 07:34 UTC, andyhan-23 commented on src/router/index.js
> +  return match ? new match.route.Controller(root, param) : new notFound(root);
네 , 알겠습니다.

2023-11-07 09:23 UTC, andyhan-23 commented on src/router/index.js
> +export const navigate = (path, param) => {
해당 pr타이틀과 연관이 없다 생각이 들어 삭제하였습니다.

2023-11-07 09:24 UTC, andyhan-23 commented on src/router/index.js
> +  return match ? new match.route.Controller(root, param) : new notFound(root);
네, 수정하겠습니다.

2023-11-07 09:35 UTC, andyhan-23 commented on src/router/index.js
> +export const navigate = (path, param) => {
우선 저는 있어야 한다고 생각하였습니다.
- navigate 함수는 상세 페이지로 이동하는데 있어서 라우터 구현의 핵심 기능이라 생각이 들어 해당 파일안에 넣었는데 혹시 필요가 없나요?

2023-11-07 09:57 UTC, andyhan-23 commented on src/router/index.js
> +    const isMatch = path.match(pathToRegex(route.path));
> 패스는 스트링을 예상했는데 오브젝트인가요?

```javascript
console.log(typeof path==="string") //true
console.log(typeof render(window.location.pathname)==="object") //true
```

2023-11-08 22:45 UTC, closed without merging