[Feat]jest 설치 및 설정변경
f-lab-edu/toss-tech-project pull request #14
Opened 2023-11-03 12:34 UTC by andyhan-23

# 설명
- 추후에 작성할 테스트 코드를 위해 jest를 설치하였습니다.
-  jest에서 import문을 쓰면 발생하는 에러를 해결하기 위해,  설정을 추가해주었습니다.
## 무슨 종류의 PR인지?

- [X] 🕹️ Feat 
- [ ] 📌 Fix
- [ ] 🔖 Documentation Update
- [ ] 🎨 Style 
- [ ] 🔎 Code Refactor 
- [ ] ✅ Test 
- [ ] 🤖 Build 
- [ ] 📦 Chore
- [ ] ⏩ Revert 

# 어떻게 테스트 되었는가?

- [ ] 테스트 코드 작성
- [ ] 로컬환경에서 수동 테스트 진행

# 티켓 번호
[JAE-27](https://linear.app/jaehyeok/issue/JAE-27/[1]-jest-%EC%84%A4%EC%B9%98)

2023-11-07 23:26 UTC, f-lab-woody requested changes

2023-11-07 23:26 UTC, f-lab-woody commented on package.json
> +  "type": "module",
이건 해당 PR에 필요한가요?

2023-11-07 23:26 UTC, f-lab-woody commented on jest.config.cjs
> +    "<rootDir>/(tests/unit/**/*.spec.(js|jsx)|**/__tests__/*.(js|jsx))",
테스트파일 이름 컨벤션이 어떻게 될까요?

2023-11-07 23:26 UTC, f-lab-woody commented on jest.config.cjs
> +    "<rootDir>/(tests/unit/**/*.spec.(js|jsx)|**/__tests__/*.(js|jsx))",
^이렇게 다양하게 표시할 필요가 있을까요?

2023-11-08 06:33 UTC, andyhan-23 commented on package.json
> +  "type": "module",
해당 PR에 필요하다고 생각하였습니다.
- 이유는 처음에 Jest설치후 import문을 쓰면 에러가 발생하였습니다. 그래서 그 이유를 찾아보았더니 Jest는 Node.js 환경에서 동작하기 때문에 CommonJS 방식으로 모듈을 사용합니다. 그러하여 이 부분을 해결하기 위해 방법을 찾다가 package.json 파일 설정에서 type을 module로 바꾸어주는 방향으로 해결하려하였습니다.

2023-11-08 06:52 UTC, andyhan-23 commented on jest.config.cjs
> +    "<rootDir>/(tests/unit/**/*.spec.(js|jsx)|**/__tests__/*.(js|jsx))",
> 테스트파일 이름 컨벤션이 어떻게 될까요?
파일이름.test.js 입니다.

2023-11-08 15:49 UTC, andyhan-23 commented on jest.config.cjs
> +    "<rootDir>/(tests/unit/**/*.spec.(js|jsx)|**/__tests__/*.(js|jsx))",
> ^이렇게 다양하게 표시할 필요가 있을까요?

컨벤션에 맞게 필요한 부분만 표시하는것으로 수정하였습니다.

2023-11-08 16:38 UTC, f-lab-woody approved these changes

2023-11-08 17:06 UTC, merged