[Feat]모델 구현
f-lab-edu/toss-tech-project pull request #18
Opened 2023-11-14 21:48 UTC by andyhan-23

# 설명
- 데이터를 요청하고 받아오는 부분을 모델로 만들어서 구현을 하였습니다.
- 데이터를 요청하는 `request` 와 응답받는 `response` 를 유틸함수로 만들어 메인 데이터와 디테일 데이터들을 가져오는데 사용할 수 있게 만들었습니다.
- 모델을 생성자 함수로 만들어 추후에 만들 컨트롤러 안에서 모델 인스턴스가 메서드로 사용을 하려 합니다.
- 테스트 코드의 내용은 아래와 같습니다.
1. 올바른 api로 요청하였을경우 메인 데이터를 잘 받아오는지 확인 
2. 올바른 api로 요청하였을겨우 디테일 데이터를 잘 받아오는지 확인
3. 생성자 함수 안에 만들어진 메서드들이 추후에 생성할 인스턴스가 사용할 수 있는지 확인
> Todo:   JAE-28 티켓에서 컨트롤러 구현 예정
[JAE-28](https://linear.app/jaehyeok/issue/JAE-28/[5]-%EB%B0%9B%EC%95%84%EC%98%A8-%EB%9D%BC%EC%9A%B0%ED%84%B0%EC%99%80-%EB%AA%A8%EB%8D%B8%EC%9D%84-%EB%B0%94%ED%83%95%EC%9C%BC%EB%A1%9C-%EC%96%B4%EB%96%BB%EA%B2%8C-%ED%99%94%EB%A9%B4%EC%97%90-%EB%B3%B4%EC%97%AC%EC%A4%84%EA%B2%83%EC%9D%B8%EC%A7%80-%EC%BB%A8%ED%8A%B8%EB%A1%A4%EB%9F%AC-%EA%B5%AC%ED%98%84)

## 무슨 종류의 PR인지?

- [X] 🕹️ Feat 
- [ ] 📌 Fix
- [ ] 🔖 Documentation Update
- [ ] 🎨 Style 
- [ ] 🔎 Code Refactor 
- [ ] ✅ Test 
- [ ] 🤖 Build 
- [ ] 📦 Chore
- [ ] ⏩ Revert 

# 어떻게 테스트 되었는가?

- [X] 테스트 코드 작성
- [ ] 로컬환경에서 수동 테스트 진행

# 티켓 번호
[JAE-29](https://linear.app/jaehyeok/issue/JAE-29/[5]-%EB%8D%B0%EC%9D%B4%ED%84%B0%EB%A5%BC-%EC%9A%94%EC%B2%AD%ED%95%98%EA%B3%A0-%EB%B0%9B%EC%95%84%EC%98%A4%EB%8A%94-%EB%B6%80%EB%B6%84%EC%9D%84-%EB%AA%A8%EB%8D%B8%EB%A1%9C-%EB%A7%8C%EB%93%A4%EC%96%B4%EC%84%9C-%EA%B5%AC%ED%98%84)

2023-11-15 01:04 UTC, f-lab-woody requested changes
저희 이미 추상화된 functions들 만들지 않았나요?
왜 또 만들죠?

2023-11-15 01:04 UTC, f-lab-woody commented on src/model/__tests__/detail.test.js
> +    const mockData = { data: { detail: `Detail data for id ${id}` } };
해당데이터가 테스트코드가 실행될때마다 정의될 필요가 있나요?

2023-11-15 01:04 UTC, f-lab-woody commented on src/model/__tests__/detail.test.js
> +jest.mock("axios");
msw를 활용해서 테스트코드를 작성해주실래요?

2023-11-15 01:04 UTC, f-lab-woody commented on src/model/__tests__/detail.test.js
> +    axios.get.mockResolvedValue(mockData);
이렇게 하시면 뭘 테스트하시는걸까요?

2023-11-15 01:04 UTC, f-lab-woody commented on src/model/__tests__/index.test.js
> +import axios from "axios";
msw를 활용해서 test코드 작성해보시는건 어떨까요?

2023-11-15 01:04 UTC, f-lab-woody commented on src/model/__tests__/main.test.js
> +import axios from "axios";
상동

2023-11-15 01:04 UTC, f-lab-woody commented on src/model/detail.js
> +    const detailData = await responseData(`/detail/${id}`);
responseData-> response와 data는 같은말아닌가요? response가 동사일까요?

2023-11-15 01:04 UTC, f-lab-woody commented on src/model/detail.js
> +    const detailData = await responseData(`/detail/${id}`);
동사로 바꾼다고 한들 의미가 잘 전달되지 않습니다

다른네이밍이 필요합니다

2023-11-15 01:04 UTC, f-lab-woody commented on src/model/detail.js
> +    const detailData = await responseData(`/detail/${id}`);
detailData또한 다른 이름이 좋겠습니다

2023-11-15 01:04 UTC, f-lab-woody commented on src/model/main.js
> +    const mainData = await responseData("/main");
상동

2023-11-15 01:04 UTC, f-lab-woody commented on src/model/main.js
> +    return mainData.articles;
articles는 mainData안쪽에 항상 있나요?

있다면 destructuring을 고려해보는건 어때요?

2023-11-15 01:04 UTC, f-lab-woody commented on src/model/main.js
> +      console.error(`can not getMainData:${error}`);
왜 can not은 일반 영어이고 getMainData는 캐멀케이스인가요?

2023-11-15 01:04 UTC, f-lab-woody commented on src/model/request-data.js
> +const reqeustData = path => {
계속 data를 붙여줘야하는이유가 있나요?

2023-11-15 01:04 UTC, f-lab-woody commented on src/model/request-data.js
> +    return axios.get(path);
이건 await이 필요없나요?

2023-11-15 01:04 UTC, f-lab-woody commented on src/model/request-data.js
> +    return axios.get(path);
promise를 리턴하는거 아니예요?

2023-11-15 01:04 UTC, f-lab-woody commented on src/model/request-data.js
> +      console.error(`can not request data:${error}`);
여기는 또 정상 문장인 이유가있을까요?

2023-11-15 04:44 UTC, andyhan-23 commented on src/model/detail.js
> +    const detailData = await responseData(`/detail/${id}`);
articles로 바꾸었습니다.

2023-11-15 04:50 UTC, andyhan-23 commented on src/model/main.js
> +    const mainData = await responseData("/main");
디스트럭처리 할당을 통해 articles 로 수정하였습니다.

2023-11-15 04:52 UTC, andyhan-23 commented on src/model/detail.js
> +    const detailData = await responseData(`/detail/${id}`);
retrieve 로 바꾸었습니다.

2023-11-15 04:53 UTC, andyhan-23 commented on src/model/main.js
> +    return mainData.articles;
수정하였습니다.

2023-11-15 05:12 UTC, andyhan-23 commented on src/model/request-data.js
> +    return axios.get(path);
> promise를 리턴하는거 아니예요?

네, 맞습니다, 허나 리턴한 프로미스를 가지고 처리 결과를 쓰이는 곳이 이 함수가 아닌 `getMainData` 및 `getDetailData` 에서 쓰일 예정이라 그 쪽에서 await 을 해주었습니다.

2023-11-15 05:23 UTC, andyhan-23 commented on src/model/request-data.js
> +const reqeustData = path => {
이 부분은 고민해보니 request 와 data가 동일한 의미를 갖는다 생각이 들어 data를 지우고 request는 명사이니 loadData 로 네이밍을 바꾸었습니다.

2023-11-15 05:23 UTC, andyhan-23 commented on src/model/request-data.js
> +      console.error(`can not request data:${error}`);
일관성있게 통일하겠습니다.

2023-11-15 21:11 UTC, andyhan-23 commented on src/model/__tests__/detail.test.js
> +    const mockData = { data: { detail: `Detail data for id ${id}` } };
정의할 필요 없게 기존에 만든 유틸함수를 가져와 테스트 하는 방식으로 수정하였습니다.

2023-11-15 21:11 UTC, andyhan-23 commented on src/model/__tests__/detail.test.js
> +jest.mock("axios");
네, 알겠습니다.

2023-11-15 21:13 UTC, andyhan-23 commented on src/model/__tests__/index.test.js
> +import axios from "axios";
수정하였습니다.

2023-11-15 21:15 UTC, andyhan-23 commented on src/model/__tests__/detail.test.js
> +    axios.get.mockResolvedValue(mockData);
get방식으로 요청을 보냈을 경우 제가 지정한 id에 막제 데이터를 받아오는지 확인 하는 테스트 인데, 이 부분또한 사전에 정의한 `mock데이터 안에 들어있는 데이터들을 올바른 api로 요청하였을경우 잘 받아오는지 확인하는 테스트.` 와 하는 행위가 다른것 같아 테스트 방식을 아예 수정하였습니다.

2023-11-16 02:52 UTC, andyhan-23 commented on src/model/main.js
> +      console.error(`can not getMainData:${error}`);
이 부분은 아예 잘 못 쓴것이라 삭제하였으며 try catch 에러를 하나의 유틸함수에서만 사용 하도록 수정하였습니다.

2023-11-18 01:48 UTC, f-lab-woody requested changes

2023-11-18 01:48 UTC, f-lab-woody commented on src/model/__tests__/detail.test.js
> +const fixPath = "http://localhost";
main, detail에서 같이 쓰시는거면 tests 파일안에 constants file 만드시고 import하셔서 쓰시는게 좋겠습니다. DRY

2023-11-18 01:48 UTC, f-lab-woody commented on src/model/__tests__/detail.test.js
> +const { DETAIL } = URL;
여기서 destructuring을 하게되면 이해도를 많이 낮추게됩니다

2023-11-18 01:48 UTC, f-lab-woody commented on src/model/__tests__/detail.test.js
> +);
server.js라는 파일을 같은레벨인 __tests__로 만든다음 switch로 json을 리턴해주는 펑션을 만든후 main 과 detail에서 import해서 사용하세요. DRY

2023-11-18 01:48 UTC, f-lab-woody commented on src/model/__tests__/main.test.js
> +import getMainList from "../main";
상동

2023-11-18 01:48 UTC, f-lab-woody commented on src/model/axios.js
> +import axios from "axios";
파일이름이 axios면 어떤작업이 되어있는지 다른 개발자가 봤을때 헷갈릴수 있어요. request나 fetch등으로 변경해서 사용하세요

2023-11-18 01:48 UTC, f-lab-woody commented on src/model/axios.js
> +      console.error(`인터셉터하여 응답도중 에러 발생: ${error}`);
nit, 어떤 리퀘스트에서 에러가 발생했는지 나타낼 수 있나요?

2023-11-18 01:48 UTC, f-lab-woody commented on src/model/axios.js
> +      console.error(`인터셉터하여 응답도중 에러 발생: ${error}`);
console error 펑션하나만 있다면 스콥안에 넣지 말아주세요

2023-11-18 01:48 UTC, f-lab-woody commented on src/model/detail.js
> +  const { DETAIL } = URL;
상동

2023-11-18 01:48 UTC, f-lab-woody commented on src/model/load-data.js
> +      console.error(`loadData 함수에서 에러 발생:${error}`);
nit, 어떤 작업에서 에러가 발생했는지 써주실 수 있지 않나요? -- 에러내용이 추상적이여서 디버깅이 힘들어 보입니다

2023-11-18 01:48 UTC, f-lab-woody commented on src/model/load-data.js
> +const loadData = async path => {
얘는 어디서 쓴거죠?

2023-11-18 01:48 UTC, f-lab-woody commented on src/model/url.js
> +  BASE: "/tossblog/v1",
키는 소문자로 써주셔야 이해되기 쉽습니다

2023-11-18 01:48 UTC, f-lab-woody commented on src/model/url.js
> +Object.freeze(URL);
object declaring하는과정에서 freeze 해주시는게 좋습니다

2023-11-18 20:58 UTC, andyhan-23 commented on src/model/__tests__/detail.test.js
> +const fixPath = "http://localhost";
수정하였습니다.

2023-11-18 20:59 UTC, andyhan-23 commented on src/model/__tests__/detail.test.js
> +const { DETAIL } = URL;
객체의 프로퍼티를 가져오는 방법으로 수정하였습니다.

2023-11-18 20:59 UTC, andyhan-23 commented on src/model/__tests__/detail.test.js
> +);
수정하였습니다.

2023-11-18 21:00 UTC, andyhan-23 commented on src/model/axios.js
> +import axios from "axios";
수정하였습니다.

2023-11-18 21:00 UTC, andyhan-23 commented on src/model/axios.js
> +      console.error(`인터셉터하여 응답도중 에러 발생: ${error}`);
수정하였습니다.

2023-11-18 21:01 UTC, andyhan-23 commented on src/model/url.js
> +  BASE: "/tossblog/v1",
수정하였습니다.

2023-11-18 21:01 UTC, andyhan-23 commented on src/model/url.js
> +Object.freeze(URL);
수정하였습니다.

2023-11-18 22:03 UTC, andyhan-23 commented on src/model/load-data.js
> +const loadData = async path => {
loadData 함수를 만들기만 하고 사용하는 곳이 없었는데, 이 함수를 사용할 수 있게 수정하였습니다.

2023-11-18 22:03 UTC, andyhan-23 commented on src/model/load-data.js
> +      console.error(`loadData 함수에서 에러 발생:${error}`);
수정하였습니다.

2023-11-21 01:32 UTC, f-lab-woody commented on src/model/__tests__/fix-path.js
> +export const fixPath = "http://localhost";
constant variable이 export될 경우 CAPITAL_SNAKE_CASE를 써주세요

2023-11-21 01:32 UTC, f-lab-woody commented on src/model/__tests__/fix-path.js
> +export const fixPath = "http://localhost";
^위와같이 할경우 쉽게 expoert된 상수/변수인지 아닌지 쉽게 알 수 있습니다

2023-11-21 01:32 UTC, f-lab-woody commented on src/model/load-data.js
> +  } catch (error) {
어떤 패스에서 에러가 발생했는지 구분할 수 있지 않나요?

2023-11-21 01:32 UTC, f-lab-woody commented on src/model/request.js
> +      if (response.status === 201)
201이 맞나요?

2023-11-21 01:32 UTC, f-lab-woody commented on src/model/request.js
> +      if (response.status === 201)
status코드는 어디서 공부하신걸까요?

2023-11-21 01:32 UTC, f-lab-woody commented on src/model/url.js
> +const url = Object.freeze({
export될 constant variable은 CAPITAL_SNAKE_CASE로 써주셔야 한눈에 알아보기가 편합니다

2023-11-21 01:32 UTC, f-lab-woody commented on src/model/url.js
> +const url = Object.freeze({
왜 파일이름이 url일까요?

constant.js로 만든 후 앞으로 추가적으로 발생할 상수를 모아놔야하지 않아요?

url이란 파일명을 봤을때 상수만 모아놨다 생각하실 수 있나요? -- 저는 어려울것같습니다

2023-11-21 01:32 UTC, f-lab-woody commented on src/model/detail.js
> +  const articleDetail = await loadData(`${URL.detail}/${id}`);
return await을 하시면 한줄로 쓸 수 있지 않을까요?

2023-11-21 12:35 UTC, f-lab-woody commented on src/model/load-data.js
> +  } catch (error) {
^ 콘솔에러 앞부분을 놓쳤네요, 무시하시면 되겠습니다

2023-11-21 22:35 UTC, andyhan-23 commented on src/model/__tests__/fix-path.js
> +export const fixPath = "http://localhost";
수정하였습니다.

2023-11-21 22:36 UTC, andyhan-23 commented on src/model/request.js
> +      if (response.status === 201)
수정하였습니다.

2023-11-21 22:52 UTC, andyhan-23 commented on src/model/detail.js
> +  const articleDetail = await loadData(`${URL.detail}/${id}`);
수정하였습니다.

2023-11-21 22:53 UTC, andyhan-23 commented on src/model/url.js
> +const url = Object.freeze({
수정하였습니다.

2023-11-21 22:53 UTC, andyhan-23 commented on src/model/url.js
> +const url = Object.freeze({
수정하였습니다.

2023-11-22 02:41 UTC, f-lab-woody approved these changes
nit코멘트 들이라 approve합니다

2023-11-22 02:41 UTC, f-lab-woody commented on src/model/__tests__/detail.test.js
> +import { URL } from "../constant";
nit, constants 파일명은 단수보단 복수로 적어주시는게 나중에 상수가 추가될 가능성이 있음을 의미할 수 있습니다

2023-11-22 02:41 UTC, f-lab-woody commented on src/model/load-data.js
> +    const result = await instance.get(path);
nit, 멘토링시간에도 이미 말씀드렸던 내용이지만
return await ...하시는게 좀더 깔끔하겠습니다

2023-11-22 03:48 UTC, merged