[Feat]헤더 컴포넌트 구현
f-lab-edu/toss-tech-project pull request #21
Opened 2023-11-22 23:53 UTC by andyhan-23

# 설명
- 추후에 화면에 보여질 헤더를 컴포넌트로 구현하였습니다.
- 5개의 단계로 나누어 css를 적용하였습니다.
<img width="1554" alt="스크린샷 2023-11-23 오전 8 48 48" src="https://github.com/f-lab-edu/toss-tech-project/assets/98483125/956a7a03-986b-4e98-8d71-0a462b286453">

## 무슨 종류의 PR인지?

- [X] 🕹️ Feat 
- [ ] 📌 Fix
- [ ] 🔖 Documentation Update
- [ ] 🎨 Style 
- [ ] 🔎 Code Refactor 
- [ ] ✅ Test 
- [ ] 🤖 Build 
- [ ] 📦 Chore
- [ ] ⏩ Revert 

# 어떻게 테스트 되었는가?

- [ ] 테스트 코드 작성
- [X] 로컬환경에서 수동 테스트 진행
 

> 실행 결과

<img width="756" alt="스크린샷 2023-11-23 오전 8 35 17" src="https://github.com/f-lab-edu/toss-tech-project/assets/98483125/ffeb5573-ac59-4e83-8810-a4647e5a87b0">

# 티켓 번호
[JAE_39](https://linear.app/jaehyeok/issue/JAE-39/[5]-%ED%97%A4%EB%8D%94-%EC%BB%B4%ED%8F%AC%EB%84%8C%ED%8A%B8)

2023-11-22 23:58 UTC, andyhan-23 commented on src/views/components/header/index.js
> +  const imageLogo = document.getElementById("header"); //Todo:app의 레이아웃인 header,nav,main,footer는 JAE-37 에서 구현 예정
[JAE-37참고 링크](https://linear.app/jaehyeok/issue/JAE-37/[2]-%EB%A7%8C%EB%93%A4%EC%96%B4%EC%A7%84-%EB%AA%A8%EB%93%A4-%EC%BB%A8%ED%8B%80%EB%A1%A4%EB%9F%AC-%EB%B7%B0-%EB%9D%BC%EC%9A%B0%ED%84%B0%EB%A5%BC-%ED%95%98%EB%82%98%EC%9D%98-app-%ED%8C%8C%EC%9D%BC-%EC%97%90%EC%84%9C-%EA%B5%AC%ED%98%84%ED%95%A0%EC%88%98-%EC%9E%88%EA%B2%8C-%EC%97%B0%EA%B2%B0%ED%95%98%EA%B8%B0)

2023-11-23 00:03 UTC, andyhan-23 commented on src/views/components/header/index.js
> +        <img src="${HEADER_LOGO}" alt="header_logo" id="logo_img" class="logo_click" />
Todo: 클래스 태그로 부여한 `logo_click`은 루트 페이지로 이동할수 있게끔 하기 위한 방법으로 컨트롤러 쪽에서 구현 예정입니다.
[JAE_36](https://linear.app/jaehyeok/issue/JAE-36/[3]-%EB%A9%94%EC%9D%B8-%ED%8E%98%EC%9D%B4%EC%A7%80%EC%97%90%EC%84%9C-%EC%83%81%EC%84%B8-%ED%8E%98%EC%9D%B4%EC%A7%80-%EB%84%98%EC%96%B4%EA%B0%80%EB%8A%94-%EB%B0%A9%EB%B2%95-%EA%B5%AC%ED%98%84-%EB%B0%8F-toss-%EB%A1%9C%EA%B3%A0-%ED%81%B4%EB%A6%AD%EC%8B%9C-%EB%A9%94%EC%9D%B8-%ED%8E%98%EC%9D%B4%EC%A7%80%EB%A1%9C-%EB%84%98%EC%96%B4%EA%B0%80%EB%8A%94-%EB%B0%A9%EB%B2%95-%EA%B5%AC%ED%98%84)

2023-11-23 03:42 UTC, f-lab-woody requested changes

2023-11-23 03:42 UTC, f-lab-woody commented on src/views/components/header/index.css
> +#container_default{
container로 네이밍 변경해주세요

2023-11-23 03:42 UTC, f-lab-woody commented on src/views/components/header/index.js
> +        <img src="${HEADER_LOGO}" alt="header_logo" id="logo_img" class="logo_click" />
이건 아이디로 불가능한가요? 결국 element를 select할려고 하시는거 아닌가요?

2023-11-23 03:42 UTC, f-lab-woody commented on src/views/components/header/index.css
> +    height: 35px;
컨테이너에서 해당 이미지의 크기 변경해주세요

2023-11-23 03:42 UTC, f-lab-woody commented on src/views/components/header/index.css
> +    height: 35px;
숫자는 짝수로 넣어주세요

2023-11-23 03:42 UTC, f-lab-woody commented on src/views/components/header/index.css
> +    width: 92%;
이렇게 하는게 맞나요? width를 100%으로 주시고 상위 컨테이너에서 조절해보는건 어때요?

2023-11-23 03:42 UTC, f-lab-woody commented on src/views/components/header/index.css
> +    height: 59px;
숫자는 홀수말고 짝수로 해주셔야 추후 일어날 수 있는 문제를 줄일 수 있습니다

2023-11-23 03:42 UTC, f-lab-woody commented on src/views/components/header/index.css
> +    position: sticky;
position sticky만하게되면 추후 특정 모바일 브라우저에서문제를 발생시킬 수 있어요.

상위 컨테이너에 position relative를 설정해주셔야합니다

2023-11-24 13:26 UTC, andyhan-23 commented on src/views/components/header/index.css
> +    position: sticky;
수정하였습니다.

2023-11-24 13:27 UTC, andyhan-23 commented on src/views/components/header/index.css
> +    height: 59px;
수정하였습니다.

2023-11-24 13:32 UTC, andyhan-23 commented on src/views/components/header/index.css
> +    width: 92%;
수정하였습니다.

2023-11-24 13:35 UTC, andyhan-23 commented on src/views/components/header/index.css
> +    height: 35px;
수정하였습니다.

2023-11-24 13:36 UTC, andyhan-23 commented on src/views/components/header/index.css
> +#container_default{
수정하였습니다.

2023-11-24 13:41 UTC, andyhan-23 commented on src/views/components/header/index.js
> +        <img src="${HEADER_LOGO}" alt="header_logo" id="logo_img" class="logo_click" />
고민을 해보니까, 로고 클릭은 헤더 컴포넌트에서 유일하게 쓰이는 것인데 클래스로 선택한것은 잘못된 선택이라 생각이 들어 수정하였습니다.

2023-11-25 03:48 UTC, f-lab-woody commented on src/views/components/header/index.css
> +    width: 92%;
완료된것 맞을까요?

2023-11-25 03:50 UTC, f-lab-woody requested changes

2023-11-25 03:50 UTC, f-lab-woody commented on src/views/components/header/index.js
> +                <img src="${HEADER_LOGO}" alt="header_logo" id="logo_click" />
여기 css는 어디있죠?

2023-11-25 03:50 UTC, f-lab-woody commented on src/views/components/header/index.js
> +<div id="header_container">
전부 div 로 처리하는게 맞나요?

2023-11-25 03:50 UTC, f-lab-woody commented on src/views/components/header/index.js
> +                <img src="${HEADER_LOGO}" alt="header_logo" id="logo_click" />
html5공부하신것 활용해보시죠

2023-11-27 10:03 UTC, andyhan-23 commented on src/views/components/header/index.css
> +    width: 92%;
제가 이해한 바로는 하위 컨테이너의 너비를 100%로 맞추고 크기의 조절은 상위 컨테이너에서 하라는 것으로 이해하였습니다. 그러하여 상위 컨테이너인 `outer_container` 에서 너비를 92%로 맞추고  하위 컨테이너인 `inner_container`에서 그 너비를 그대로 사용할수 있게 100%로 하여 크기를 조절하였는제 혹시 제가 잘못 이해하고 수정한 부분이 있을까요?

2023-11-27 10:04 UTC, andyhan-23 commented on src/views/components/header/index.js
> +<div id="header_container">
인라인 요소는 span 태그로 수정하였습니다.

2023-11-27 13:43 UTC, f-lab-woody commented on src/views/components/header/index.css
> +    width: 92%;
네, inner_container에서 100을 주시고 그 상위 컨테이너에서 패딩 등으로 width를 조절할 수 있지 않을까요?

2023-11-27 13:46 UTC, f-lab-woody requested changes

2023-11-27 13:46 UTC, f-lab-woody commented on src/views/components/header/index.js
> +<div id="header_container">
왜 span이죠?
해당 블록은 시멘틱 웹 관점으로 잘 적용되었을까요?

2023-11-27 13:46 UTC, f-lab-woody commented on src/views/components/header/index.js
> +          <img src="${HEADER_LOGO}" alt="header_logo" id="logo_click" />
이미지 태그의 CSS는 필요없나요?

https://github.com/f-lab-edu/toss-tech-project/pull/21#discussion_r1404712523

2023-11-28 07:37 UTC, andyhan-23 commented on src/views/components/header/index.js
> +          <img src="${HEADER_LOGO}" alt="header_logo" id="logo_click" />
이미지 태그의 CSS는 모두 `header_logo_컨테이너` 안에서 처리하였습니다. 그러하여 따로 이미지 태그의 CSS는 필요 없다 생각하였습니다.

2023-11-28 08:31 UTC, andyhan-23 commented on src/views/components/header/index.js
> +                <img src="${HEADER_LOGO}" alt="header_logo" id="logo_click" />
웹 접근성을 고려한 HTML 태그를 작성하여, 모든 태그를 div 태그로 처리하는 것이 아닌, 해당 태그가 무엇을 가리키는 것이지 쉽게 표현하기 위해 `header` 태그로 감싸안으며 이미지 로고 같은 경우 클릭시 루트 경로로 이동한다는 점에서 nav 태그로 만들었습니다. 

- 이미지 태그 같은 경우 이미지를 정확히 못알아보는 시간 장애인들을 위해 alt 속성을 추가하여 해당 이미지가 무엇인지 글로 설명할 수 있게 만들었습니다.

2023-11-28 08:37 UTC, andyhan-23 commented on src/views/components/header/index.js
> +<div id="header_container">
시맨틱 웹 관점을 고려하였을때 header 태그를 사용하여 전체를 감싸았으며 그 안에서 로고 컨테이너 같은 경우 클릭시 루트 경로로 이동할수 있으니 nav태그로 감싸았습니다.

2023-11-28 09:19 UTC, andyhan-23 commented on src/views/components/header/index.css
> +    width: 92%;
하위 컨테이너인 `header_inner_container` 에서는 너비의 크기를 100%로 부여하였고 상위 컨테이너인`header_outer_container` 에서 패딩을 10px로 부여하고 너비의 크기를 92%로 부여해 상위 컨테이너 안에서 크기를 조절하는 방법으로 수정하였습니다.
<img width="1188" alt="스크린샷 2023-11-28 오후 6 17 09" src="https://github.com/f-lab-edu/toss-tech-project/assets/98483125/244c1de9-7dde-4da6-ad40-222f50fa2ca6">

2023-11-28 10:02 UTC, andyhan-23 commented on src/views/components/header/index.js
> +  const imageLogo = document.getElementById("header"); //Todo: JAE-37 티켓이서 app 레이아웃 구현 예정입니다.
[JAE_37](https://linear.app/jaehyeok/issue/JAE-37/[2]-%EB%A7%8C%EB%93%A4%EC%96%B4%EC%A7%84-%EB%AA%A8%EB%93%A4-%EC%BB%A8%ED%8B%80%EB%A1%A4%EB%9F%AC-%EB%B7%B0-%EB%9D%BC%EC%9A%B0%ED%84%B0%EB%A5%BC-%ED%95%98%EB%82%98%EC%9D%98-app-%ED%8C%8C%EC%9D%BC-%EC%97%90%EC%84%9C-%EA%B5%AC%ED%98%84%ED%95%A0%EC%88%98-%EC%9E%88%EA%B2%8C-%EC%97%B0%EA%B2%B0%ED%95%98%EA%B8%B0)

2023-11-28 12:53 UTC, f-lab-woody commented on src/views/components/header/index.css
> +    width: 92%;
제가 코멘트 드린것 다시 한번 읽어보시겠어요?

2023-11-28 12:58 UTC, f-lab-woody requested changes

2023-11-28 12:58 UTC, f-lab-woody commented on src/views/components/header/index.js
> +      <nav id="header_logo_container">
여긴 nav일 필요가 없습니다

2023-11-28 12:58 UTC, f-lab-woody commented on src/views/components/header/index.js
> +  const imageLogo = document.getElementById("header"); //Todo: JAE-37 티켓이서 app 레이아웃 구현 예정입니다.
아이디는 헤더를 찾는데 왜 변수명은 이미지 로고일까요?

2023-11-28 13:01 UTC, f-lab-woody commented on src/views/components/header/index.js
> +          <img src="${HEADER_LOGO}" alt="header_logo" id="logo_click" />
아뇨 필요합니다. 
작은 이미지가 나올경우 우리가 예축하지 못한 사이드 이펙트가 있을 수 있습니다.

이미지 너비를 100%로 주고 컨테이너에서 조정해주세요.

2023-11-28 13:04 UTC, f-lab-woody commented on src/views/components/header/index.css
> +    width: 120px;
width는 100으로
제한은 max width로 해주세요

2023-11-29 11:18 UTC, andyhan-23 commented on src/views/components/header/index.js
> +          <img src="${HEADER_LOGO}" alt="header_logo" id="logo_click" />
수정하였습니다.

2023-11-29 11:18 UTC, andyhan-23 commented on src/views/components/header/index.js
> +      <nav id="header_logo_container">
수정하였습니다.

2023-11-29 11:18 UTC, andyhan-23 commented on src/views/components/header/index.js
> +  const imageLogo = document.getElementById("header"); //Todo: JAE-37 티켓이서 app 레이아웃 구현 예정입니다.
네이밍을 headerElement 로 변경하였습니다.

2023-11-29 11:19 UTC, andyhan-23 commented on src/views/components/header/index.css
> +    width: 120px;
수정하였습니다.

2023-11-29 11:23 UTC, andyhan-23 commented on src/views/components/header/index.css
> +    width: 92%;
네, 멘토님 다시 한번 코멘트 읽고 반영하여 수정하였습니다.
- 상위 컨테이너 에서 좌우 패딩 값을 46px로 부여해 max-width가 1140px 였을때 하위 컨테이너의 너비가 1048px로 전체 너비의 92%로만 하위 컨테이너에서 차지 할수 있게끔 수정하였습니다.

2023-11-29 13:23 UTC, f-lab-woody requested changes

2023-11-29 13:23 UTC, f-lab-woody commented on src/views/components/header/index.css
> +    max-width: 120px;
width 100%는 어디있죠?

2023-11-29 13:23 UTC, f-lab-woody commented on src/views/components/header/index.css
> +}
이부분이 header/index.css안에서 나와야할 내용인가요?

2023-11-29 13:23 UTC, f-lab-woody commented on src/views/components/header/index.js
> +        <a href="/">
상단 컴포넌트에 cursor:pointer가 적용되어있는데 그러면 a 는 상위 컴포넌트를 감싸주어야하지 않나요?

2023-11-29 13:23 UTC, f-lab-woody commented on src/views/components/header/index.css
> +#header{
#header{

->

#header {

보기편하게 프리티어 적용해주세요

2023-11-29 13:23 UTC, f-lab-woody commented on src/views/components/header/index.js
> +  const headerElement = document.getElementById("header"); //Todo: JAE-37 티켓이서 app 레이아웃 구현 예정입니다.
그냥 header라고 표현하시면 됩니다

2023-11-30 09:55 UTC, andyhan-23 commented on src/views/components/header/index.js
> +  const headerElement = document.getElementById("header"); //Todo: JAE-37 티켓이서 app 레이아웃 구현 예정입니다.
수정하였습니다.

2023-11-30 09:59 UTC, andyhan-23 commented on src/views/components/header/index.css
> +}
관련된 스타일만 해당 파일에 넣는 방식으로 수정하였습니다.

2023-11-30 10:00 UTC, andyhan-23 commented on src/views/components/header/index.css
> +#header{
수정하였습니다.

2023-11-30 11:00 UTC, andyhan-23 commented on src/views/components/header/index.css
> +    max-width: 120px;
추가하였습니다.

2023-11-30 11:39 UTC, andyhan-23 commented on src/views/components/header/index.js
> +        <a href="/">
cursor: pointer를 상단 컴포넌트가 아닌 a태그에 적용시키는 방법으로 수정하였습니다.

2023-12-01 01:49 UTC, f-lab-woody commented on src/views/components/header/index.css
> +}
추후 처리계획인 티켓 코멘트로 달아주세요

2023-12-01 01:49 UTC, f-lab-woody commented on src/views/components/header/index.js
> +        <a href="/">
이해하신것 맞으시죠?

2023-12-01 01:51 UTC, f-lab-woody requested changes

2023-12-01 01:51 UTC, f-lab-woody commented on src/views/components/header/index.css
> +#header_logo_container {
a 태그에 스타일 주신게 맞을까요?

스타일은 바로 아래 컨테이너인 div태그에 넣어주세요

2023-12-01 02:19 UTC, andyhan-23 commented on src/views/components/header/index.js
> +        <a href="/">
a태그를 어떻게 포함시키느냐에 따라 커서를 잡는 범위가 다르게 이루어진다고 이해하였습니다.

2023-12-03 11:48 UTC, andyhan-23 commented on src/views/components/header/index.css
> +#header_logo_container {
수정하였습니다.

2023-12-03 11:49 UTC, andyhan-23 commented on src/views/components/header/index.css
> +        JAE-37에서 진행 예정.
[JAE-37](https://linear.app/jaehyeok/issue/JAE-37/[2]-%EB%A7%8C%EB%93%A4%EC%96%B4%EC%A7%84-%EB%AA%A8%EB%93%A4-%EC%BB%A8%ED%8B%80%EB%A1%A4%EB%9F%AC-%EB%B7%B0-%EB%9D%BC%EC%9A%B0%ED%84%B0%EB%A5%BC-%ED%95%98%EB%82%98%EC%9D%98-app-%ED%8C%8C%EC%9D%BC-%EC%97%90%EC%84%9C-%EA%B5%AC%ED%98%84%ED%95%A0%EC%88%98-%EC%9E%88%EA%B2%8C-%EC%97%B0%EA%B2%B0%ED%95%98%EA%B8%B0)

2023-12-03 14:58 UTC, f-lab-woody approved these changes, later dismissed

2023-12-03 14:58 UTC, f-lab-woody commented on src/views/components/header/index.js
> +        <img src="${HEADER_LOGO}" alt="토스 로고 아이콘" />
토스로고아이콘은 반복된 설명입니다.

로고아이콘이면 충분합니다

2023-12-03 15:04 UTC, andyhan-23 commented on src/views/components/header/index.js
> +        <img src="${HEADER_LOGO}" alt="토스 로고 아이콘" />
반영하였습니다.

2023-12-04 11:06 UTC, f-lab-woody approved these changes

2023-12-04 11:16 UTC, merged