[Feat]리스트 컴포넌트 구현
f-lab-edu/toss-tech-project pull request #25
Opened 2023-12-06 08:41 UTC by andyhan-23

# 설명
- 추후 화면에 보여질 리스트 컴포넌트를 구현하였습니다.
- 날짜를 보여주는 문구를 함수화 시켰습니다.

## 무슨 종류의 PR인지?

- [X] 🕹️ Feat 
- [ ] 📌 Fix
- [ ] 🔖 Documentation Update
- [ ] 🎨 Style 
- [ ] 🔎 Code Refactor 
- [ ] ✅ Test 
- [ ] 🤖 Build 
- [ ] 📦 Chore
- [ ] ⏩ Revert 

# 어떻게 테스트 되었는가?

- [ ] 테스트 코드 작성
- [X] 로컬환경에서 수동 테스트 진행
> 실행화면 
<img width="1330" alt="스크린샷 2023-12-06 오후 5 30 27" src="https://github.com/f-lab-edu/toss-tech-project/assets/98483125/48343a0b-e7d1-4504-b5f4-ae2774295fd4">

# 티켓 번호
[JAE-43](https://linear.app/jaehyeok/issue/JAE-43/[2]-%EB%A6%AC%EC%8A%A4%ED%8A%B8-%EC%BB%B4%ED%8F%AC%EB%84%8C%ED%8A%B8)

2023-12-06 08:46 UTC, andyhan-23 commented on src/views/components/list/index.js
> +//Todo: JAE_28 티켓에서 컨트롤러 구현을 통해 list를 받아올 예정입니다.
[JAE-28](https://linear.app/jaehyeok/issue/JAE-28/[5]-%EB%B0%9B%EC%95%84%EC%98%A8-%EB%9D%BC%EC%9A%B0%ED%84%B0%EC%99%80-%EB%AA%A8%EB%8D%B8%EC%9D%84-%EB%B0%94%ED%83%95%EC%9C%BC%EB%A1%9C-%EC%96%B4%EB%96%BB%EA%B2%8C-%ED%99%94%EB%A9%B4%EC%97%90-%EB%B3%B4%EC%97%AC%EC%A4%84%EA%B2%83%EC%9D%B8%EC%A7%80-%EC%BB%A8%ED%8A%B8%EB%A1%A4%EB%9F%AC-%EA%B5%AC%ED%98%84)

2023-12-07 11:34 UTC, f-lab-woody requested changes
스크린샷 기준 이미지 비율이 이상합니다 확인해주세요

2023-12-09 04:33 UTC, f-lab-woody requested changes

2023-12-09 04:33 UTC, f-lab-woody commented on src/views/components/list/format-date.js
> +  const day = inputDate.substring(6, 8);
안좋은 방법입니다.
서버가 포맷을 바꾸면 어떻게 반영하실 건가요?

2023-12-09 04:33 UTC, f-lab-woody commented on src/views/components/list/index.js
> +  const listArr = Object.values(list).reverse();
reverse를 해야하나요?

2023-12-09 14:40 UTC, andyhan-23 commented on src/views/components/list/format-date.js
> +  const day = inputDate.substring(6, 8);
date-fns를 라이브러리를 설치하여 format함수를 사용하여 형식을 지정해주는 방식으로 수정하였습니다.

2023-12-09 14:41 UTC, andyhan-23 commented on src/views/components/list/index.js
> +  const listArr = Object.values(list).reverse();
map 메서드를 이용하여 배열을 뒤집지 않고 역순으로 받아오는 방법을 시도해보았습니다.

2023-12-09 16:07 UTC, f-lab-woody commented on src/views/components/list/index.js
> +  });
리듀스를 통해 해당 iteration을 한번에 만들 수 있지 않나요?

2023-12-09 17:04 UTC, andyhan-23 commented on src/views/components/list/index.js
> +  });
리듀스의 인자인 accumulator에 해당 iteration을 모두 받아 하나의 결과값을 리턴 할수 있게 수정하였습니다.

2023-12-10 16:57 UTC, f-lab-woody approved these changes
nit, 처음 요청드렸던 방법은 fixture 데이터 변화입니다.

보통 내림차순 오름차순은 백쪽에서 정해서 주고, 실제 데이터를 뒤집는 작업은 프론트에서 지향하진 않습니다. 지향하지 않는 이유는 앞으로에서 사용한 리액트에서 스테이트를 어떻게 관리하는지 공부해보시면 좀더 이해하시기 쉬울 것 같습니다.

2023-12-10 17:51 UTC, merged