[Feat] 콘텐트 컴포넌트 구현
f-lab-edu/toss-tech-project pull request #28
Opened 2023-12-16 11:37 UTC by andyhan-23

# 설명
-  추후 화면에 보여질 콘텐트를 컴포넌트로 구현하였습니다.
- 5단계로 나뉘어 컨테이너를 적용하였습니다.
<img width="898" alt="스크린샷 2023-12-11 오전 4 19 12" src="https://github.com/f-lab-edu/toss-tech-project/assets/98483125/48979b9e-b7da-4ba7-8914-c28e06cec28f">

## 무슨 종류의 PR인지?

- [X] 🕹️ Feat 
- [ ] 📌 Fix
- [ ] 🔖 Documentation Update
- [ ] 🎨 Style 
- [ ] 🔎 Code Refactor 
- [ ] ✅ Test 
- [ ] 🤖 Build 
- [ ] 📦 Chore
- [ ] ⏩ Revert 

# 어떻게 테스트 되었는가?

- [ ] 테스트 코드 작성
- [X] 로컬환경에서 수동 테스트 진행
>실행화면
<img width="916" alt="스크린샷 2023-12-11 오전 4 06 56" src="https://github.com/f-lab-edu/toss-tech-project/assets/98483125/b91299ea-3cb2-4dd6-bd43-db3f4ad4c331">

# 티켓 번호
[JAE-45](https://linear.app/jaehyeok/issue/JAE-45/[2]-%EC%BD%98%ED%85%90%ED%8A%B8-%EC%BB%B4%ED%8F%AC%EB%84%8C%ED%8A%B8)

2023-12-16 16:59 UTC, f-lab-woody requested changes

2023-12-16 16:59 UTC, f-lab-woody commented on src/views/components/content/index.js
> +    created_date: createdDate,
alpha

2023-12-16 16:59 UTC, f-lab-woody commented on src/views/components/content/index.js
> +        <img src="${thumbnailImage}" alt="상세 페이지에 들어있는 이미지" />
alt=썸네일

2023-12-16 16:59 UTC, f-lab-woody commented on src/views/components/content/index.js
> +  const main = document.getElementById("main"); //Todo: JAE-37 티켓에서 app 레이아웃 구현 예정입니다.
해당 코멘트 아직도 필요한가요?

2023-12-16 16:59 UTC, f-lab-woody commented on src/views/components/content/index.js
> +    thumbnail_image: thumbnailImage,
thumbnailImage -> image

2023-12-16 16:59 UTC, f-lab-woody commented on src/views/components/content/index.js
> +const contentComponet = (articleItem, body) => {
아직 왜 body라는 네이밍이 나왔는지 설득 안됩니다

2023-12-16 16:59 UTC, f-lab-woody commented on src/views/components/content/index.js
> +const contentComponet = (articleItem, body) => {
두 파라미터 머지해서 보낼 수 없나요?

2023-12-17 09:26 UTC, andyhan-23 commented on src/views/components/content/index.js
> +    created_date: createdDate,
알파벳순으로 정렬하여 수정하였습니다.

2023-12-17 09:27 UTC, andyhan-23 commented on src/views/components/content/index.js
> +        <img src="${thumbnailImage}" alt="상세 페이지에 들어있는 이미지" />
수정하였습니다.

2023-12-17 09:27 UTC, andyhan-23 commented on src/views/components/content/index.js
> +    thumbnail_image: thumbnailImage,
수정하였습니다.

2023-12-17 09:29 UTC, andyhan-23 commented on src/views/components/content/index.js
> +const contentComponet = (articleItem, body) => {
데이터를 병렬처리하여 하나의 객체 안에세 모두 받을수 있게 수정하였습니다.

2023-12-17 09:31 UTC, andyhan-23 commented on src/views/components/content/index.js
> +  const main = document.getElementById("main"); //Todo: JAE-37 티켓에서 app 레이아웃 구현 예정입니다.
필요없다 생각이 들어 제거하였습니다.

2023-12-17 09:32 UTC, andyhan-23 commented on src/views/components/content/index.js
> +const contentComponet = (articleItem, body) => {
하나의 파라미터로 통일하였습니다.

2023-12-17 12:10 UTC, f-lab-woody approved these changes

2023-12-17 12:31 UTC, merged