[Feat]msw 추가 및 mock 데이터 생성
f-lab-edu/toss-tech-project pull request #6
Opened 2023-10-27 20:19 UTC by andyhan-23

# 설명
- msw 를 설치하였습니다.
- mock 데이터를 json 형태로 만들었습니다.
## 무슨 종류의 PR인지?

- [x] 🕹️ Feat 
- [ ] 📌 Fix
- [ ] 🔖 Documentation Update
- [ ] 🎨 Style 
- [ ] 🔎 Code Refactor 
- [ ] ✅ Test 
- [ ] 🤖 Build 
- [x] 📦 Chore
- [ ] ⏩ Revert 

# 어떻게 테스트 되었는가?

- [ ] 테스트 코드 작성
- [ ] 로컬환경에서 수동 테스트 진행

# 티켓 번호
[JAE-15](https://linear.app/jaehyeok/issue/JAE-15/[01]-msw-%EC%84%A4%EC%B9%98-%EB%B0%8F-mock-%EB%8D%B0%EC%9D%B4%ED%84%B0-%EC%B6%94%EA%B0%80)

2023-10-29 02:39 UTC, f-lab-woody requested changes
이전에 approve받은 PR부터 먼저 머지하신 후 해당 PR진행해주세요

2023-10-29 02:39 UTC, f-lab-woody commented on .eslintrc.json
> +// }
이전 커밋 머지이후 다시요청주세요

2023-10-29 02:39 UTC, f-lab-woody commented on public/mockServiceWorker.js
> + * - Please do NOT serve this file on production.
> Please do NOT serve this file on production.

계획이 어떻게 되시나요?

2023-10-29 02:39 UTC, f-lab-woody commented on src/mock/get-data.js
> +export function getData(data) {
왜 argument이름이 data이죠? 더좋은 네이밍 없나요?

2023-10-29 02:39 UTC, f-lab-woody commented on src/mock/get-data.js
> +      return console.error("NO DATA");
에러는 개발환경에서만 보여줘야하지 않을까요?

2023-10-29 02:39 UTC, f-lab-woody commented on src/mock/handler.js
> +  rest[method](`${path}`, (req, res, ctx) => {
> `${path}`

왜 path는 스트링 리터럴로 감싸주나요?

2023-10-29 02:39 UTC, f-lab-woody commented on src/mock/index.js
> +    const mockJSON = [main, detail].map((data) => {
data 만 바로 리턴하는데 굳이 스콥으로 감싸줄 필요가 있나요?

2023-10-29 02:39 UTC, f-lab-woody commented on src/mock/index.js
> +    const mockJSON = [main, detail].map((data) => {
data가 function 인가요? 
적절한 네이밍 맞나요?

2023-10-29 02:39 UTC, f-lab-woody commented on src/mock/index.js
> +    const worker = setupWorker(...mockJSON);
setupWorker로 들어가는 arg값에 스프레드 연산자가 들어간 이유는 뭔가요?

2023-10-29 02:39 UTC, f-lab-woody commented on src/mock/index.js
> +    console.error(`worker error: ${error}`);
위 코멘트 동일

2023-10-29 02:39 UTC, f-lab-woody commented on src/mock/index.js
> +  return false;
에러 스코프 가아니라 밖에서 return 하는 이유가 따로 있을까요?

2023-10-29 02:39 UTC, f-lab-woody commented on src/app.js
> +}
의미 없는 파일입니다. 해당 PR에 필요한가요?

2023-10-29 03:24 UTC, andyhan-23 commented on .eslintrc.json
> +// }
이전 커밋 머지 완료하여서 해당 pr에서는 삭제하였습니다.

2023-10-29 05:27 UTC, andyhan-23 commented on public/mockServiceWorker.js
> + * - Please do NOT serve this file on production.
수도 코드로 계획을 작성해봤습니다.
- msw 라이브러리 설치
- 서비스 워커 등록
- 이후 브라우저에서 axios로 데이터 요청
- 요청이 오면 서비스 워커가 가로챈다.
- 서비스 워커는 가로챈 요청을 복사해서 msw 라이브러리로 보낸다.
- 등록된 핸들러를 통해 모의 응답을 제공한다.
- 제공받은 mocking 응답을 브라우저에게 그대로 전달한다.

> 이 방법으로 만든 데이터를 가지고 요청을 보내고 응답을 받아 화면에 보여주려 합니다.

2023-10-29 05:29 UTC, andyhan-23 commented on src/mock/get-data.js
> +export function getData(data) {
data -> target 으로 바꾸려 합니다.

2023-10-29 06:10 UTC, andyhan-23 commented on src/mock/get-data.js
> +      return console.error("NO DATA");
vite의 환경변수인 `import.meta.env.DEV`를 사용하여 true일때만 에러를 보여주게 처리하였습니다.

2023-10-29 06:51 UTC, andyhan-23 commented on src/mock/index.js
> +    console.error(`worker error: ${error}`);
수정하였습니다.

2023-10-29 06:52 UTC, andyhan-23 commented on src/mock/index.js
> +  return false;
수정하였습니다.

2023-10-29 06:55 UTC, andyhan-23 commented on src/mock/index.js
> +    const mockJSON = [main, detail].map((data) => {
수정하였습니다.

2023-10-29 07:06 UTC, andyhan-23 commented on src/mock/handler.js
> +  rest[method](`${path}`, (req, res, ctx) => {
수정하였습니다.

2023-10-29 07:09 UTC, andyhan-23 commented on src/app.js
> +}
파일을 삭제하였습니다.

2023-10-29 12:50 UTC, andyhan-23 commented on src/mock/index.js
> +    const worker = setupWorker(...mockJSON);
저희는 이번 프로젝트에서 요청을 /main 과 /detail/:id 이렇게 두개의 방식으로 요청하는 핸들러 객체가 두개 필요합니다.  객체 안에는 요청 method와 ,path 그리고 그에 해당하여 반환되는 데이터이며, 두 개의 객체를 배열 형태로 집어넣어 순회하는 방식으로 진행이 되어 스프레드 연산자를 사용하여 객체들을 하나씩 빼는 방식으로 진행 하려했습니다. 혹시 이 부분에서 제가 잘못 이해하고 사용한 것이 있을까요?

2023-10-29 20:45 UTC, f-lab-woody commented on public/mockServiceWorker.js
> + * - Please do NOT serve this file on production.
제가 질문드린 내용 다시한번 읽어보시겠어요?

2023-10-29 20:52 UTC, f-lab-woody commented on src/mock/index.js
> +    const worker = setupWorker(...mockJSON);
제가 어떤걸 질문한건지 다시한번 읽어보실 수 있나요?

2023-10-29 21:01 UTC, f-lab-woody requested changes

2023-10-29 21:01 UTC, f-lab-woody commented on src/api/get-detail.js
> +export default function getDetail() {
어차피 함수를 리턴하는데 굳이 스콥을 따로 잡아놓은 이유가 있나요?

2023-10-29 21:01 UTC, f-lab-woody commented on src/api/get-main.js
> +export default function getMain() {
상동

2023-10-29 21:01 UTC, f-lab-woody commented on src/mock/handler.js
> +export const handler = (method, path, data, callback) => {
상동

2023-10-29 21:01 UTC, f-lab-woody commented on .prettierrc.json
> +    "arrowParens": "avoid"
이건 해당 PR에 필요한 요소인가요? 이전 PR에 포함되어야하지 않아요?
아니라면 따로 PR만들어서 먼저 머지후적용해주세요

2023-10-30 06:33 UTC, andyhan-23 commented on src/api/get-detail.js
> +export default function getDetail() {
변경 하였습니다.

2023-10-30 06:34 UTC, andyhan-23 commented on .prettierrc.json
> +    "arrowParens": "avoid"
새로운 브랜치 만들어서 Pr요청 보내드렸습니다. 리뷰후 merge허락해주시면 새로운 브랜치 먼저 머지 후 진행하겠습니다.

2023-10-30 13:02 UTC, f-lab-woody commented on src/api/get-detail.js
> +export default function getDetail() {
```javascript
export const getDetail = () => handler(...);
```

2023-10-30 16:41 UTC, andyhan-23 commented on src/api/get-main.js
> +export default function getMain() {
중괄호를 제거하는 부분으로 바꾸었습니다.

2023-10-30 16:41 UTC, andyhan-23 commented on src/mock/handler.js
> +export const handler = (method, path, data, callback) => {
중괄호를 제거하는 부분으로 바꾸었습니다.

2023-10-31 12:43 UTC, andyhan-23 commented on src/mock/index.js
> +    const worker = setupWorker(...mockJSON);
스프레드 연산자란 집합에서 펼처진 개별적인 값들의 목록으로 만드는 것입니다. 그래서 집합인 배열을 펼쳐서 개별적인 핸들러 객체의 목록으로 만든후, setupWorker라는 함수의 인수 목록으로 전달하기 위하여 스프레드 연산자를 사용했습니다.

2023-10-31 12:45 UTC, andyhan-23 commented on public/mockServiceWorker.js
> + * - Please do NOT serve this file on production.
환경변수를 설정하여 process.env.NODE_ENV가 development 일때만 파일을 로드할수 있도록 조건을 작성할 계획입니다.

2023-11-01 00:29 UTC, f-lab-woody requested changes

2023-11-01 00:29 UTC, f-lab-woody commented on src/mock/get-data.js
> +    switch (json) {
이전 네이밍이 더 나아보입니다.
매개변수로 string을 받지 않나요? json인가요?

2023-11-01 00:29 UTC, f-lab-woody commented on src/mock/index.js
> +      const mockHandler = [main, detail].map(RestHandler => RestHandler());
> RestHandler => RestHandler())

1. 왜 Pascal case죠?
2. restHandler -> handler로 하는건 어떨까요?

2023-11-01 00:29 UTC, f-lab-woody commented on src/mock/index.js
> +    if (process.env.NODE_ENV === "development") {
1. 이건왜 process.env이고 에러핸들링에선 import.meta.env.DEV를 한거죠?

2. 실제 서버 만들어서 프로덕션에서 돌릴건가요?

2023-11-01 02:55 UTC, andyhan-23 commented on src/mock/index.js
> +      const mockHandler = [main, detail].map(RestHandler => RestHandler());
변수 네이밍은 수정하였습니다.

2023-11-01 02:59 UTC, andyhan-23 commented on src/mock/get-data.js
> +    switch (json) {
매개변수로 string을 받습니다. 

- 이전 네이밍인 target으로 바꾸었습니다.

2023-11-01 04:01 UTC, andyhan-23 commented on src/mock/index.js
> +    if (process.env.NODE_ENV === "development") {
1. 요부분은 제가 착각했습니다. 🙏
2. 아니요. 똑같이 msw를 이용해서 프로덕션에서 돌릴생각입니다

2023-11-01 14:03 UTC, f-lab-woody approved these changes
nit, 코멘트는 수정해도 되고 안해도 되고 선택 입니다.
하지만 reply는 달아야해요.

만약 자신의 의견이 있다면 작성하시고 없다면 티켓을 따로 생성해서 address하게끔 티켓넘버를 reply하시면 됩니다. -- 해당 티켓 안쪽 description 에는 무엇을 어떻게 고칠건지, reference link는 무엇인지 적어주셔야 나중에 잊어버리지 않아요.

2023-11-01 14:03 UTC, f-lab-woody commented on src/mock/get-data.js
> +import detailJSON from "../../__fixtures__/detail.json";
nit, 더 좋은 네이밍 없을까요?

2023-11-01 14:41 UTC, andyhan-23 commented on src/mock/get-data.js
> +import detailJSON from "../../__fixtures__/detail.json";
더 좋은 네이밍은 `mainData` `detailData`라고 생각이 드는데 TICKET:JAE-25 에서 수정할 생각입니다. 
[JAE-15](https://linear.app/jaehyeok/issue/JAE-25/[1]%EB%B3%80%EC%88%98-%EB%84%A4%EC%9D%B4%EB%B0%8D-%EC%88%98%EC%A0%95)

2023-11-01 14:57 UTC, andyhan-23 commented on src/api/get-detail.js
> +export default function getDetail() {
코멘트 반영하여 수정하였습니다.

2023-11-01 15:20 UTC, merged